### PR TITLE
sf geometry class warning. Fixes #47

### LINKED ISSUE #47: sf geometry class warning
Expanding on https://github.com/ropensci/osmplotr/issues/46, here is a suggestion to change a cryptic error to a useful warning.
Essence of the previous issue: if `sf` is not loaded, the subsetting method `[.sf` is not available and  `[.data.frame` is used. This causes a cryptic error in
`add_osm_objects -> get_obj_type -> tolower -> strsplit`

Here's a MWE. Make sure sf is not loaded when runnning it:

```r
library(osmplotr)
bbox <- get_bbox(c(12.5, 53.1, 12.6, 53.2))
dat_F <- extract_osm_objects(key="landuse", bbox=bbox, quiet=TRUE, value="forest")
map <- osm_basemap(bbox=bbox, bg='gray95')
map <- add_osm_objects(map, dat_F[1:10,], col='green')

Error in strsplit(class(obj$geometry)[i], "sfc_")[[1]] : 
  subscript out of bounds
```

I suggest adding a warning / error in `get_obj_type` in [line 19](
https://github.com/cran/osmplotr/blob/master/R/check-fns.R#L19)

```r
obj <- dat_F[1:10,]

if(!inherits(obj$geometry, "sfc")) warning("object class is sf, but the geometry",
  " column class is '", toString(class(obj$geometry)), "' instead of 'sfc'.\n",
  "This can occur e.g. after subsetting sf objects without the sf package loaded.")
```

### PR DESCRIPTION
**Pull request by brry**

### CODE REVIEW

**Comment by brry** [comment]
I don't see the proposed change showing up in the master branch - maybe because there were two PRs going on at the same time? Should I resubmit a PR?
https://github.com/ropensci/osmplotr/pull/49/commits/998601a962e360680b0c9e3c9201ae4762d0a89d

**Comment by mpadge** [comment]
It's because this PR has already been merged (on Feb 7; see above), and appears all fine in master branch [here](https://github.com/ropensci/osmplotr/blob/master/R/check-fns.R#L19-L22).

**Comment by brry** [comment]
Sorry, I must have been looking at some older version of the master.

**Comment by mpadge** [comment]
No worries!

**Pull request merged**
