### PR TITLE
Opinionated changes to vignette code using magrittr

### PR DESCRIPTION
**Pull request by beemyfriend**
Added magrittr to the second vignette on 'data maps.' 

Made some stylistic changes to the code that, in my opinion, would make it easier to follow.

section 1.3: dat_H and dat_HP were never explicitly created in the knitted vignette. I added them to the beginning of 

section 1.7: deleted highways4 as it was never use. IAlso, I don't think connect_highways(highways, bbox)  (shown in the knitted vignette) and hwys[[i]] (used on the back end) produce the same result.

### CODE REVIEW

**Comment by mpadge** [comment]
Thanks for the contribution! I like the re-alignment of all args, it definitely makes it easier to read, and so i'd like to merge the PR after a few changes:
1. Please revert all the `dat_H` and `dat_HP` stuff to the way it was. This relies on the lazy-loaded internal data that are used to construct the vignettes. The code *looks* like it doesn't use or need them, but creating them during execution makes the code too slow for CRAN to accept it. They are thus necessary behind the scenes, yet I've written the vignette so the reader needs neither to read nor to know about them.
2. `highways4` can indeed be deleted, as can your comments on Lines#704-706. The two now differ because I re-wrote the whole routines, but the plots are nevertheless the same. If you discover any substantial differences, then just open an issue and describe it there.
3. Could you please remove all of the figures from the PR because they are unchanged.

**Comment by beemyfriend** [comment]
1. I reverted most of the backend (pre-knitted) dat_H and dat_HP stuff to the way it was. However, I still think it is necessary to explicitly define those variables in the knitted vignette. I'm not sure what you mean by 'the reader needs neither to read nor to know about them.' The code at sections 1.4, 2, 2.1, 2.2, and 2.3  explicitly mention `dat_H` and `dat_HP`. Because of this I switched the `london$dat_HP` and `london$dat_HP` of section 1.3 to `dat_H` and `dat_HP` so that it matches with the other sections. 

2. I deleted the comments. I don't think there was a substantial difference between the two, but I still noticed it while i was going through the vignette and thought it was worth mentioning. 

3. I removed all of the figures. I actually thought they were necessary to show the vignette's `.html` file, but I realize now that the `.png` files are not necessary for the knitted vignette to work.

**Comment by mpadge** [comment]
cool, thanks. and yeah, you're right with switching from `londat$dat_H*` to `dat_H*, so thanks for that too. Now only one final request: Can you remove `basic-maps.html` as well, because that's always auto-generated and doesn't need to be included.

**Comment by beemyfriend** [comment]
I got rid of the `.html`  file, I had no idea that the `.Rmd` file could stand alone in the package. That's really cool.

This is actually my first PR so thanks for your patience with me. I'll try to be more helpful in the future.

**Pull request merged**
